[project]
name = "aoc2025-python"
version = "0.1.0"
description = "Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "basedpyright>=1.36.1",
    "mypy>=1.19.1",
    "ruff>=0.14.10",
]
